# Generated by Django 3.0.8 on 2020-07-07 11:18

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Editor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='efield',
            name='Rollno',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='efield',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
